[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0.5" }

[package.metadata.risc0]
methods = ["guest"]

[[bin]]
name = "guest"
path = "guest/src/main.rs"

[dependencies]
ndarray = "0.16.1"
rmp-serde = "1.3.0"
smartcore = "0.3.2"
