[package]
name = "mlp_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.0.5", default-features = false, features = ['std'] }
smartcore = { version = "0.3.2", features = ["serde"] }
ndarray = "0.15"
rmp-serde = "1.1.2"
